version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=auto-ria-clone
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=superroot
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure