spring:
  datasource:
    url: jdbc:mysql://localhost:3307/auto-ria-clone?createDatabaseIfNotExist=true
    username: user
    password: user
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: TRACE